### ISSUE TITLE
Hide from app menu

### ISSUE THREAD

**Issue by kotx** [zehuanli/Google-Voice-Mark-Read#3]
This would be a good feature to have, as a setting in the app.

**Comment by zehuanli** [comment]
Sorry but I don't fully understand what you mean. Do you want this module app to be hidden from the app drawer?

**Comment by kotx** [comment]
Yup, a few LSPosed modules I have like Let Me Downgrade have a setting to hide the shortcut from the app drawer.

**Comment by zehuanli** [comment]
That's interesting. I do have a number of modules that I wanted to hide since there are no settings needed for them. I'll look into this.

**Comment by zehuanli** [comment]
6dac5d897907aa94873d3e8b4c073c900fc7ca4a

I ended up just removing the only activity (so there will be no app icon) since it makes little sense to exist.
