### ISSUE TITLE
Module not working on new phone

### ISSUE THREAD

**Issue by ImYak** [zehuanli/Google-Voice-Mark-Read#4]
New pixel 7 phone coming from pixel 5 on Android 13. I've successfully rooted and installed zygisk but for some reason it's not working. Is this because of new voice version or because of new phone?

**Comment by zehuanli** [comment]
Neither is, I believe, as I'm currently using the latest version of Voice on Android 13.

Can you confirm if you have enabled this module and added Google Voice to the list? If so, can you try to restart Voice (force stop and then open it) and see if there is any log with the prefix `[VOGO]` in the module logs?

**Comment by ImYak** [comment]
I have the module enabled and voice is checked in the list. The log does show [VOGO] notifications hook started and finished, and also shows a handful of other vogo related lines such as "Loading module com. upbad. apps.vogo fron..."

**Comment by zehuanli** [comment]
Sounds like the module has been loaded and trying to hook functions in your Voice app. Could you please share the apk file of your Voice?

**Comment by ImYak** [comment]
Since you mentioned the APK file I decided to reinstall a fresh copy of voice. The copy I had was from a backup, so doing this solved the issue, thanks so much for you quick replies and for making this module, I use it everyday!
